name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    env:
      GO111MODULE: auto
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Build
      run: go build -o apg -v github.com/wneessen/apg-go/cmd/apg

    - name: Test
      run: go test -v github.com/wneessen/apg-go/cmd/apg
