name: Go

on:
  release:
    types: [ created ]

jobs:
  releases-matrix:
    name: Release Go Binary (BSDs)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [freebsd, netbsd, openbsd]
        goarch: ["386", amd64, arm, arm64]
    steps:
      - uses: actions/checkout@v2
      - uses: wangyoucao577/go-release-action@v1.20
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          binary_name: "apg"
          extra_files: LICENSE README.md
          sha256sum: true
          md5sum: false
          build_command: 'go build github.com/wneessen/apg-go/cmd/apg'
