name: Go

on:
  release:
    types: [ created ]

jobs:
  releases-matrix:
    name: Release Go Binary (Darwin)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [darwin]
        goarch: ["386", amd64]
    steps:
      - uses: actions/checkout@v2
      - uses: wangyoucao577/go-release-action@v1.15
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          binary_name: "apg"
          extra_files: LICENSE README.md
          sha256sum: true
          md5sum: false
